### ISSUE TITLE
Release Real-robot Code？

### ISSUE THREAD

**Issue by hwpengTristin** [arc-l/remp#1]
The code works perfectly in the simulation environment. Could you provide the code for the real robot as well?

**Comment by baichuan05** [comment]
[robot_test.py.zip](https://github.com/user-attachments/files/15709894/robot_test.py.zip)

You may take a look at this one, but it requires a hardware setup (pendant), and it is hard to show over here. So I just left this for your reference.

**Comment by hwpengTristin** [comment]
Your work is very interesting. Thank you for the reference!
